# Generated by Django 5.1.1 on 2024-10-30 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import registration.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=registration.models.code_generator,
                                          help_text='random code used for registration and for password reset',
                                          max_length=15, verbose_name='code')),
                ('is_validated', models.BooleanField(default=False)),
                ('code_used', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='registration_profile', to=settings.AUTH_USER_MODEL,
                                              verbose_name='user')),
            ],
        ),
    ]
