name: pocketmind

dependencies:
  - python=3.12.5
  - pip=24.2
  - psycopg2=2.9.9
  - pip:
      - django==5.1.1
      - djangorestframework==3.15.2
      - djangorestframework-simplejwt==5.3.1
      - drf-yasg==1.21.7
      - flake8==7.1.1
      - gunicorn==23.0.0
      - pillow==10.3.0
      - django-cors-headers==4.5.0
      - django_extensions
      - drf-yasg
      - pillow
