# Generated by Django 5.1.1 on 2024-11-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories',
                                   to='color.color')),
            ],
        ),
    ]
