# Generated by Django 5.1.1 on 2024-10-31 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="amount_spent",
        ),
        migrations.RemoveField(
            model_name="category",
            name="budget",
        ),
    ]
