# Generated by Django 5.1.1 on 2024-11-04 22:58

from django.db import migrations, models


def populate_financial_tips(apps, schema_editor):
    # Get the FinancialTip model
    FinancialTip = apps.get_model('your_app_name', 'FinancialTip')

    # Predefined tips to populate the database
    predefined_tips = [
        {"category": "General", "tip": "Try to save at least 20% of your income each month."},
        {"category": "Groceries", "tip": "Buy in bulk to save on groceries."},
        {"category": "Entertainment", "tip": "Limit your entertainment expenses to 10% of your monthly budget."},
        {"category": "Savings", "tip": "Set aside a portion of your income for an emergency fund."},
        {"category": "Transportation", "tip": "Use public transportation or carpool to save on commuting costs."},
    ]

    # Insert predefined tips into the FinancialTip table
    for tip in predefined_tips:
        FinancialTip.objects.create(**tip)


class Migration(migrations.Migration):

    dependencies = [
        # Add your migration dependencies here (e.g., the migration that creates FinancialTip)
        ('dashboard', '0002_aiinsight_created_at'),
    ]

    operations = [
        # migrations.RunPython(populate_financial_tips),
        migrations.CreateModel(
            name='FinancialTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('tip', models.TextField()),
            ],
        ),
    ]
