# Generated by Django 5.1.1 on 2024-11-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_financialtip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIInsight',
        ),
    ]
