# Generated by Django 5.1.1 on 2024-11-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=100)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=100)),
                ('color', models.TextField()),
            ],
        ),
    ]
