# Generated by Django 5.1.1 on 2024-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='spend',
            field=models.FloatField(default=0),
        ),
    ]
